### ISSUE TITLE
Setup TravisCI to run tests against Windows

### ISSUE THREAD

**Issue by tjwebb** [trailsjs/trails#110]
I naively added 
```
os: 
- linux
- osx
- windows
```
but there are a few issues:

1. The "windows" build seems to be occurring on a linux machine. maybe this somehow is how it's supposed to work, but I don't know. https://travis-ci.org/trailsjs/trails/builds/116054489

2. I don't know if "nvm" even works on windows. If not, windows needs to run some install process, somehow.

Tests for Trails should run automatically against windows. Deployment should only happen from a linux-based build.

**Comment by tjwebb** [comment]
Bounty: https://www.bountysource.com/issues/31897782-setup-travisci-to-run-tests-against-windows

**Comment by jaumard** [comment]
In fact the build who fail is the mac os x build because nvm is not install in Travis VM. But yeah windows build run on linux it's strange...
For osx I see this https://github.com/travis-ci/travis-ci/issues/2311#issuecomment-171180704
You need to add : 

```
env:
  - NODE_VERSION="4.0"
  - NODE_VERSION="4.1"
  - NODE_VERSION="4.2"
  - NODE_VERSION="5.4"
os:
  - linux
  - osx
  - windows
matrix:
  fast_finish: true
before_install:
  - git clone https://github.com/creationix/nvm.git /tmp/.nvm;
    source /tmp/.nvm/nvm.sh;
    nvm install $NODE_VERSION;
    nvm use --delete-prefix $NODE_VERSION;
install:
  - npm install
script:
  - npm test
```

If I can I will look the windows problem but windows support seems new to Travis.

**Comment by jaumard** [comment]
Hum they didn't talk about windows in there doc https://docs.travis-ci.com/user/multi-os/ maybe windows is not out yet...

**Comment by tjwebb** [comment]
Perhaps, then, there's another CI service that can automatically run these tests on Windows?

**Comment by jaumard** [comment]
Sorry I didn't know a CI service who allow Windows environment (for Node or everything else)... Maybe someone else will know this.

There some things that will append like windows on Travis (they seem to be close to release it). 

But there also some docker container base on windows that will come out https://www.docker.com/microsoft we can imagine create a docker for testing Trails on windows with https://circleci.com/docs/docker#deployment-to-a-docker-registry
This solution can be heavy to setup and maintain...

**Comment by mscdex** [comment]
[AppVeyor](appveyor.com) does CI on Windows VMs and is free for open source projects.

**Comment by tjwebb** [comment]
Cool, thanks @mscdex for the link, I'll check them out.

btw, it's been like two decades since I've seen the word "mscdex" anywhere so thanks for reminding me of the good ol days of debugging windows boot issues :)

**Comment by ryayak1460** [comment]
Seconding AppVeyor.  Travis-CI does not have true Windows compatibilty yet.  Here's the issue tracking that: travis-ci/travis-ci/#216

Also, [this gist](https://gist.github.com/Azolo/2783045) has some (granted, older) notes about some of the internal reasons why Travis-CI can't really run Windows builds just yet.

**Comment by jaumard** [comment]
I have something who work with appveyor here https://ci.appveyor.com/project/jaumard/trails (not yet for node 4.4.2 because I thinks app veyor doesn't have an image for it yet)
How do you want to do this @tjwebb  ? Can you create the appveyor account and team and add me in it for me to configure it ? Or give me the rights on Trails repo ? let me know.
