### ISSUE TITLE
use Map() for storing config tree

### ISSUE THREAD

**Issue by tjwebb** [trailsjs/trails#124]
#### Problem

There's No Good Reason I need to write code like this

``` js
const foo = this.config.bar && this.config.bar.baz && this.config.bar.baz.foo
```

in order to avoid the `foo of undefined` problem. And in Trails core, there's this craziness: https://github.com/trailsjs/trails/blob/master/lib/trails.js#L17-L25.
#### Solution

If I simply collapse the config tree into a Map(), I can happily say things like

``` js
this.config.get('bar.baz.foo')
```

and it'll either exist or not, but won't throw any sort of error. I also sort of wonder if lookup may be faster than traversing a handful of object references to get to where I want. 

This approach is much cleaner and I'm considering adopting this before 1.0. I need to research the number of outstanding trailpacks and see what it would cost to upgrade all of them.

**Comment by jaumard** [comment]
Sounds good ! Better to do it now than later ! :) also a `this.config.get('bar.baz.foo', 'defaultValue') ` can be useful.

**Comment by Alaneor** [comment]
I would rather not use a `Map` for this, because there might be situations where you want to get the whole configuration object at a specific location.

For example, using a `Map` would not allow me to get the whole object located at `service1` if it should store all values individually.

```js
{
  service1: { /* many props here */ },
  service2: { /* many props here */ }
}

// Using a map:
config.get('service1.someprop') // returns some value
config.get('service1') // ??? No such key in map!

// Expected:
config.get('service1.someprop') // returns some value
config.get('service1') // returns the whole thing
```

Instead, we could use the string as a location, split it to individual property keys and recursively attempt to look the value up at that location, returning the value if found or `undefined` otherwise.

Generally I like the idea, makes the code much more easier to write and follow.

#### On backwards-compatibility

We can make it so that direct property traversal will also be supported, and the `get()` and `set()` methods will be added as a "bonus" to the configuration object. That would mean we can keep current trailpacks as they are and refactor at a later time, while officially only documenting the new way, for example.

**Comment by jaumard** [comment]
Yes we can keep background compatibility. Instead of `Map` we can simply add `get` and `set` functions who will just use `get` and `set` methods of `lodash` https://lodash.com/docs#get https://lodash.com/docs#set 
Like this we can access config directly or just by doing `this.config.get('bar.baz.foo', 'defaultValue')`

**Comment by Alaneor** [comment]
Working on this.

**Comment by tjwebb** [comment]
> I would rather not use a Map for this, because there might be situations where you want to get the whole configuration object at a specific location.

This doesn't have to be. We could store subtrees in keys as well.

**Comment by tjwebb** [comment]
See: http://jsperf.com/es6-object-v-map-get-3

`Map.get()` is about 5x faster than indexing 3-4 levels into the config object.

**Comment by Alaneor** [comment]
Just found [nconf](https://github.com/indexzero/nconf) and I must say I would rather use that instead of my attempt to reinvent the wheel in #126. Their API looks the same as the one proposed here. They even claim to support Redis for storing/retrieving configuration. I would really love to see support for loading configuration from a remote location, that should make Trails attractive for deployments in a container-based deployment scheme, ie. in CoreOS, with their etcd providing application configuration to Trails.
