### ISSUE TITLE
Install specific version of trails using yeoman

### ISSUE THREAD

**Issue by kaytrance** [trailsjs/trails#187]
#### Issue Description
How can I install latest version of trailsjs using yeoman? The thing is that upon running `yo trails` 1.0.0-beta-1 is installed (according to package.json). So is there a way to install latest version of trails via yeoman?

#### Environment
- node version: 6.1.0
- trails version: 1.0.0-beta1
- operating system: Ubuntu 15.10

**Comment by jaumard** [comment]
For now all dependencies are hardcoded here https://github.com/trailsjs/trails/blob/master/archetype/package.json#L12 to have the latest version you can run `npm update --save` after project is generated, for now they're no other way. 

Also if you want to test Trails don't use node 6 because for now there some problems with sqlite3 installation on it.

**Comment by kaytrance** [comment]
Thank you for quick response, @jaumard
