### ISSUE TITLE
Too many sqlite3 dependencies 

### ISSUE THREAD

**Issue by jaumard** [trailsjs/trails#196]
#### Issue Description
Actually any Trailpack who have models and want to make unit test need to use sqlite3 adapter. Unfortunately sqlite3 is build from source witch can fail (example with node 6), and when it occur all Trailpack who depends on sqlite3 are freeze because travis is failing.

Maybe we can use (or fork) https://github.com/balderdashy/sails-disk and use it as adapter for Trailpack tests. Like this no more sqlite3 problems.

What do you think @trailsjs/maintainers ?

PS : sqlite3 problem is now fix on npm with the last version (until next node version??) but all modules need to be updated with the last version.

#### Environment
- node version: all
- trails version: all
- operating system: all

**Comment by jaumard** [comment]
Just try on few modules, `sails-disk` can be use directly and work great for unit test. Using it for `trailpack-express` and now no sqlite3 dependency anymore.

**Comment by tjwebb** [comment]
In development, we've run into too many issues with `sails-disk`. It's really crappy, and becomes really slow once you have more than a thousand rows or so. Also the semantics aren't true to the interface -- data types and validations aren't always enforced correctly.

I know there are a lot of issues with the sqlite3 adapter also, but this is mostly due to the recent node6 upgrade, and not really related to the quality of the adapter itself. In the future, we'll come up with a better release process for supporting new node versions so that everything doesn't break when a new node version is released.

**Comment by jaumard** [comment]
@tjwebb my point of view is to use `sails-disk` only for unit test (on trailpacks) so maybe it's enough for this task ? Because you will haven't many data and you control it.
I will never use `sails-disk` for a Trails project or something like this like in Sails (for the problems you mention). I happy with sqlite3 adapter that's not the issue.
I'm not a fan of sqlite3 for trailpacks mostly because it have to be compile/build witch 1 is really slow, 2 can break more frequently than a non compiled modules and lock the all trailpack. 
I find it more clean to doesn't have all the compile scary log stack when it's not really needed ^^ but maybe with a better release process I will doesn't complain about this lol we will see :D

**Comment by jaumard** [comment]
Closing this :)
