### ISSUE TITLE
`trailmap-*` a proposal to load modules before trails initiates.

### ISSUE THREAD

**Issue by scott-wyatt** [trailsjs/trails#220]
#### Feature Request
In #208 @jaumard brings up the point that he would like to do operations before trails starts.  Right now, to do this means that you have to alter server.js, which is an "OK" solution.  The problem now is, every user who needs similar functionality will do it a different way causing fragmentation.  Then when a user shares their code, now the community is exposed to the fragmentation as well.  In my opinion, this is bad.  

#### Proposal
I think if we use the same `trailpack-module` and change trails to look for `trailmap-*` before initiating, we can reduce fragmentation and provide some very interesting and powerful new tools to the trails ecosystem that are then shareable.  
I Propose that we offer a standard strategy for implementing this functionality that gives users the ability to use their own tactics and keeps with the trails ethos. @trailsjs/webmasters if this is agreeable, then could we get this added to the roadmap?

**Comment by jaumard** [comment]
Something like : 
```
packs: [
    require('trailmap-gulp'),
    require('trailmap-...'),
    require('trailmap-...')
  ],
```
Then pass this to `server.js` like this trails can calcul all lifecycle order like trailpacks and then run them.  Most of the code already exist and used for trailpacks so this can be pretty cool (and relatively easy to implement).

**Comment by scott-wyatt** [comment]
Cool, so this looks like we have some traction.  @tjwebb could I get your input?

**Comment by tjwebb** [comment]
>  before trails starts

It all depends on what you mean by this. when is "before", anyway? If you define trailmaps in the config, some part of Trails will still have to load. Are you mainly trying to guarantee that the trailmap runs before all other trailpacks, including trailpack-core?

This is already *sort of* possible by writing the necessary logic inside of the trailpack constructor. These constructors are instantiated immediately in the `Trails` constructor, here: https://github.com/trailsjs/trails/blob/master/index.js#L94. `new Pack(...)` happens before `trailsApp.start(...)` is invoked.

So I think we're left with: do we want to start writing logic in these constructors, or should we create a new paradigm (trailmaps)? Right now I'm leaning toward the first approach in order to keep the framework more conceptually simple, and reduce framework-level code. I think that the constructor can happily call helper functions on the Trailpack, or in a util module, to keep things tidy.

Have I understand the question? :)

**Comment by scott-wyatt** [comment]
Yes, you understand the question.  I actually didn't realize that `new Pack` happens before `.start()` was invoked, so I will have to play around with that and report back.  If that works for these use cases, then we shouldn't create a new paradigm. 
The case where I can see this being useful outside of the constructors are for things like compiling. I know it sounds a bit crazy, but if I wanted to write a trails app in let's say C, Swift, or typescript, then there could be a `trailmap-*` that performs the needed operations before `new TrailsApp`. Technically speaking, you can do this by running executions with npm, but that requires a lot of tooling and it would be incredible to just include this functionality as a dependency. Thoughts?

**Comment by jaumard** [comment]
We can add another function into trailpack `preboot()` that return a promise and when all promise are executed the `start` is called. Look clean to me.

**Comment by scott-wyatt** [comment]
Okay, so I think I have an elegant solution for this that won't change trails core, keep the spirit of trails, and won't create a paradigm shift.  `trailmap-*` will be it's own preboot that can be called with npm.  Eg.  `npm start` could run `trailmaps && node server`.  A `trailmap-*` will be structured like a trailpack and can run as a trailpack with the exception of a function called `preboot`.  `preboot` only get's initiated when called by the terminal, and the rest of the functions follow traditional trailpack guidelines. A `trailmap-*` will be order of operations independent.  This way, heavy lifting of compiling etc. will not be in the start process. (Which is a huge problem in common practices of node development eg. Grunt and Gulp really shouldn't be run as part of the main process in production. Although with solution, you could still do it). This means you can do things like npm -> postinstall -> trailmaps  etc. Thoughts?

**Comment by scott-wyatt** [comment]
I've started this at <https://github.com/CaliStyle/trailmap> will continue discussion there if need be.
