### ISSUE TITLE
How do I properly use a template engine

### ISSUE THREAD

**Issue by FiatPax** [trailsjs/trails#229]
#### Issue Description
So I want to use ect engine. I went and modified my ViewController.js like this

```
'use strict'

const Controller = require('trails-controller')
const ECT = require('ect');
let renderer = ECT({ root : __dirname + '/../../views' });

module.exports = class ViewController extends Controller {

  helloWorld (request, reply) {
  	let data = { title : 'Hello, World!' };
	let html = renderer.render('template.ect', data);
    reply(html)
  }
}
```

Is this how I do it properly or is there a better approach?

#### Environment
- node version: all
- trails version: all
- operating system: all

**Comment by jaumard** [comment]
http://ectjs.com they didn't have any example for Hapi webserver so don't know if they are compatible. But they are with express so you can use `trailpack-express` instead of `trailpack-hapi` and configure your template engine into `config/web.js`. If you want to keep hapi then you way is ok if ect is not compatible directly with hapi

**Comment by FiatPax** [comment]
Thank you for the explanation, I'll either keep hapi and ect or check other hapi compatible template engines.
