### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by wamatt** [trailsjs/trails#232]
![image](https://cloud.githubusercontent.com/assets/1271434/18529479/11e67882-7a82-11e6-876b-0b4c851474e3.png)

Seems like tjwebb has taken some time off? Is this a temporary thing or is the future bright for trails?

Reason I ask, is that myself and others may be contemplating building a new project on trails, but if it's heading towards being abandoned, then obviously that would call into question that decision.

**Comment by beaverusiv** [comment]
I would say look at all the other work in the other projects under trailsjs. It seems work has just concentrated in other areas.

**Comment by jaumard** [comment]
Hi :) @beaverusiv has right. The trails repo doesn't do much by itself because trails is modular. This means a lot of the trails repos are part of trails. It doesn't have any new commit on this repo because there no need for now :) by looking at them you'll see tjwebb is not the only one who is working on trails anymore.

Hope it's help ^^

**Comment by konstantinzolotarev** [comment]
@wamatt I'd suggest to look into team activity here https://github.com/trailsjs
You will have much better vision about project and it's parts.

**Comment by scott-wyatt** [comment]
This is a great time to start talking about releasing documentation again and http://trailsjs.io. :-)

**Comment by wamatt** [comment]
Thanks for the replies folks, I checked out the other org and nice to see some activity going on.

That said, @jaumard when you say "it's done" I sort of have a different view. And that's ok! In my mind the core repo forms a shelling point for the project. I could be wrong of course, though from what I've observed, the successful and popular frameworks out there (eg Angular) are never quite 'done' and keep innovating as the JS landscape changes.

**Comment by jaumard** [comment]
@wamatt where I say "it's done" ? It's never done in software ^^ I just say for now there no more needs and that's why there no commits on this repo. 

You're right the core repo is a shelling point of trails, but it "only" do few things : 
- Logs 
- I18n
- Load trailpacks
- Merge config

All "intelligence" are moved into separate modules called "trailpacks"

**Comment by tjwebb** [comment]
@wamatt the trails core has not required much work, because it doesn't do much. As others have mentioned, we've been spending time fixing bugs in other modules and building new trailpacks.

Communicating activity across a federation of modules is tougher than with a monolith. Based on your question, as a community we should look into setting up a way to communicate the status of the whole ecosystem of modules, rather than only a single module.

**Comment by wamatt** [comment]
Thanks @tjwebb + all and appreciate the followups. To your communication point, I'd imagine a feature like 'Github org activity', would be handy for that sort of thing.

Well, I'm enjoying playing around with trails, and good to know it has an active team behind it. Going to close this. Cheers
