### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by Chartieer** [trailsjs/trails#329]
#### Issue Description
Your Website is offline, last commit is 8month ago. 
So is Trails dead?

**Comment by catrielmuller** [comment]
Short answer: Yes
Long answer: Most of the developers went over to https://fabrix.app/

**Comment by scott-wyatt** [comment]
Hi there @volkerchartier, mostly the website is down because the company that was hosting it dissolved. The website is open source, so anyone is welcome to host it.  Active development of Trails v3 has stopped, and v2 is monitored for security updates.  I and a few others decided to implement v3 in typescript for Fabrix as @catrielmuller said. It's the trails you know and love with some very small subtle changes. We're looking to grow, so feel free to join us!
