### ISSUE TITLE
Windows build issue

### ISSUE THREAD

**Issue by chuckpearce** [trailsjs/trails#91]
Attempting to run basic installation of trails, fails on npm start under Windows 10.

Output of "npm start" command: http://pastebin.com/qpknnM5n

config/footprints.js shows the "prefix" set to "/api/v1". 

Node Version: Tested on 4.x and 5.x
Windows Version: Windows 10

Reproduction Steps:
npm install -g generator-trails
npm install -g yo
yo trails
npm start

Confirmed these steps worked without issue on a linux based machine.

**Comment by jakobrosenberg** [comment]
Same issue here.

**Comment by tjwebb** [comment]
This weekend I'll try to download a Windows 10 VM and test it. If you guys have any ideas on why the issue is occurring, that'd be appreciated.

**Comment by jaumard** [comment]
The problem is coming from https://github.com/trailsjs/trailpack-router/blob/master/lib/footprints.js#L35 and https://github.com/trailsjs/trailpack-router/blob/master/lib/footprints.js#L54 

In fact `path` use `/` on linux and `\` on windows. The problem is hapi need only `/` or you have 
`Invalid path : \api\v1\default\info`.

I'm able to run it on windows by removing `path` usage on the 2 methods link above. I didn't find a `path.join` option to force slashes on Windows. For my tests I just remove path and concatenate strings and Trails is working.

**Comment by tjwebb** [comment]
thanks @jaumard.  I should use https://nodejs.org/api/url.html#url_url_resolve_from_to instead. I did not realize the `path` module was os-specific.
